on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v1.1.4
        with:
    # github user name
         github_user_name: MC-1One
    # path of the generated gif file. If left empty, the gif file will not be generated.
         gif_out_path: MC-1One/MC-1One/dist
    # path of the generated svg file. If left empty, the svg file will not be generated.
         svg_out_path: MC-1One/MC-1One/dist
